### ISSUE TITLE
regression: cannot publish to private npm registry

### ISSUE THREAD

**Issue by bobzoller** [travis-ci/dpl#309]
9930f1a broke publishing to private npm registries, as it hardcodes the public registry in the npmrc file.  a simple fix would be to respect the value of `publishConfig.registry` inside `package.json`.

/cc @clayreimann

**Comment by BanzaiMan** [comment]
@bobzoller Sorry for the regression. Do you have an example `package.json` that points to a private registry? I'll take a look.

**Comment by bobzoller** [comment]
Thanks @BanzaiMan -- here's an example.

```
{
  "name": "example-logger",
  "version": "1.0.0",
  "description": "Bunyan tossed with our special blend of spices.",
  "author": "Example Team <team@example.com>",
  [....snip...]
  "publishConfig": {
    "registry": "https://npm.example.com/",
    "always-auth": true
  }
}
```

**Comment by BanzaiMan** [comment]
@bobzoller OK! I've pushed the fix to the master branch. Could you test it with:

```yaml
deploy:
  provider: npm
  edge: true # <= new!
  ⋮ # rest
```

Thank you!

**Comment by BanzaiMan** [comment]
I've released 1.7.19.

**Comment by bobzoller** [comment]
Thanks @BanzaiMan for the quick fix!  After testing I realize there's a second issue: the .npmrc format change in 9930f1a is specific to npm2, which means anyone still on npm1 (by default that's anyone running node < v0.11 I think) still won't be able to publish.

One fix could be to write out the .npmrc with both styles, eg:
```
_auth="foo"
registry=https://npm.example.com/
//npm.example.com/:_authToken="foo"
```

npm1 will pick up `_auth`, and npm2 will prefer the '//npm.example.com' line.  technically putting an npm2 auth token in `_auth` is wrong (it's a different format), but in my testing npm2 will prefer the other line and succeed.

I tested the file format above with node 0.10.36 (npm 1.4.28), and node 0.12.7 (npm 2.11.3).

another would be to interrogate the npm version and write out two different files.

**Comment by BanzaiMan** [comment]
@bobzoller Hello! Thanks for raising this issue. I took the route to detect NPM version and write `~/.npmrc` (without the `registry` key-value pair, since it wasn't there before and will presumably picked up from `package.json`). My rudimentary testing went fine, but do you mind testing NPM 1.x and 2.x with `edge: true` again?

**Comment by bobzoller** [comment]
npm1 test went fine.  npm2 test failed.  the reason is my `registry` is specified with a trailing slash, eg `https://npm.example.com/`, and when the npm2 .npmrc is written, it has a double slash that npm does not handle.

```
//npm.example.com//:_authToken=foo
```

removing the trailing slashes all together is apparently not valid either, so it seems it'd be nice of `dpl` to normalize the trailing slashes.

**Comment by bobzoller** [comment]
side note, hopefully helpful to those that discover this thread later:  since the npm auth token format changed between npm1 and npm2, it becomes useful to specify an `on` clause within your `deploy` section to make sure the npm version and api_key format match.  deploy failures don't fail the build though, so you may not even notice...

```
language: node_js
node_js:
  - '0.10'
  - '0.12'

deploy:
  provider: npm
  api_key: "foo" # npm2 style authToken
  clean_up: false
  on:
    tags: true
    all_branches: true
    node: '0.12' # b/c an npm1 deploy will now fail
```

**Comment by BanzaiMan** [comment]
The above commit normalizes the slashes. You can test it with `edge: true`.

I'm closing this optimistically.
