### ISSUE TITLE
Unable to deploy to forge.puppet.com

### ISSUE THREAD

**Issue by zerodecimal** [travis-ci/dpl#772]
Hello,

I am unable to deploy to the Puppet forge because of an unsatisfied dependency of dpl, json/pure. An example [job log is here](https://travis-ci.org/zerodecimal/zerodecimal-oracle_inventory/jobs/351511061) if you want to take a look. I did include json_pure in my Gemfile and can see that it did get installed. I'm a little confused because dpl is installing under a different ruby version (2.2.7) than I have specified in .travis.yml (2.4.1) for the build. I'm new at this and haven't got it to work yet, so let me know if I'm missing something.

**Comment by BanzaiMan** [comment]
Hello, there. Looks like we forgot to add `json_pure` to the run time dependencies for this provider. I pushed a potential fix. Please try it with:

```yaml
deploy:
  provider: puppetforge
  edge:
    branch: puppet_forge-post-1_9_0
  user: zerodecimal
  ⋮ # rest
```

and report the result? Thanks.

As for Ruby 2.2.7, it is the version that is pre-installed on the build image, and it is the one that we perform deployment with.

**Comment by pmuller** [comment]
Deployment was working a few days ago. But today I have a similar issue: https://travis-ci.org/pmuller/puppet-aws_firewall/jobs/351907488

**Comment by pmuller** [comment]
@BanzaiMan it works for me, thanks!

**Comment by zerodecimal** [comment]
I still received [the same error](https://travis-ci.org/zerodecimal/zerodecimal-oracle_inventory/jobs/351970812).

**Comment by BanzaiMan** [comment]
@zerodecimal That job's configuration is still using the 1.9.0 release. https://github.com/zerodecimal/zerodecimal-oracle_inventory/blob/73b475f0385d9379f2c4f9c9b4b3abf457e42db7/.travis.yml#L43-L51

**Comment by zerodecimal** [comment]
Oh man you're right. I just verified that it works, thanks!

**Comment by dhollinger** [comment]
VoxPupuli is seeing the same issue: https://travis-ci.org/voxpupuli/puppet-rsyslog/jobs/352109468#L623

**Comment by BanzaiMan** [comment]
@dhollinger Please tear the fix mentioned in https://github.com/travis-ci/dpl/issues/772#issuecomment-371960721

**Comment by BanzaiMan** [comment]
Will be in 1.9.1. I'll keep the `puppet_forge-post-1_9_0` branch for a week or so after the 1.9.1 release, so that the repos with this workaround can be switched off it.
